const appointmentsEnums = {
  GET_APPOINTMENT: "GET_APPOINTMENT",
  GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
  GET_APPOINTMENT_ERROR: "GET_APPOINTMENT_ERROR",

  CREATE_APPOINTMENT: "CREATE_APPOINTMENT",
  CREATE_APPOINTMENT_SUCCESS: "CREATE_APPOINTMENT_SUCCESS",
  CREATE_APPOINTMENT_ERROR: "CREATE_APPOINTMENT_ERROR",  
};

export default appointmentsEnums;
